name: angular_gallery_section
publish_to: none

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  analyzer: ^0.40.0
  angular: ^6.0.0
  angular_components: ^1.0.0
  angular_gallery:
    path: ../angular_gallery
  build: '>=0.11.1 <2.0.0'
  build_config: '>=0.2.6 <0.5.0'
  glob: ^1.1.5
  markdown: ^3.0.0
  mustache: ^1.0.0
  path: ^1.6.1
  sass: '>=1.15.3 <2.0.0'

dependency_overrides:
  angular_components:
    path: ../angular_components
