name: angular_gallery_section
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.2.1-dev.3.0 <3.0.0'
dependencies:
  analyzer: ^0.36.0
  angular: ^5.3.0
  angular_components: 0.13.0
  angular_gallery:
    path: ../angular_gallery
  build: '>=0.11.1 <2.0.0'
  build_config: '>=0.2.6 <2.0.0'
  glob: ^1.1.5
  markdown: ^2.0.3
  mustache: ^1.0.0
  path: ^1.6.1
  sass: '>=1.15.3 <2.0.0'

dependency_overrides:
  angular_components:
    path: ../angular_components
