name: angular_gallery_section
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.1.0-dev.9.4 <3.0.0'
dependencies:
  analyzer: ^0.33.0
  angular: ^5.1.0
  angular_components: 0.10.1
  build: '>=0.11.1 <2.0.0'
  build_config: '>=0.2.6 <0.4.0'
  glob: ^1.1.5
  markdown: ^2.0.0
  mustache: ^1.0.0
  path: ^1.6.1
