name: angular_components
version: 0.6.0-alpha+3
description: >
  The official Material Design components for AngularDart. Used at Google
  in production apps.
homepage: https://webdev.dartlang.org/components
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=1.24.0 <2.0.0-dev.infinity'
dependencies:
  angular: 4.0.0-alpha+3
  angular_forms: 0.1.0
  collection: ^1.14.0
  fixnum: ^0.10.5
  intl: '>=0.14.0 <0.16.0'
  js: ^0.6.1
  logging: ^0.11.2
  meta: ^1.0.4
  observable: '>=0.14.0+1 <0.21.0'
  perf_api: ^0.1.0
  quiver: '>=0.22.0 <0.26.0'
  uuid: ^0.5.3
transformers:
- angular
