name: material_yes_no_buttons_example
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.5.0-dev.1.0 <3.0.0'
dependencies:
  angular: ^6.0.0-alpha+1
  angular_components: 0.14.0-alpha+1
  angular_gallery:
    path: ../../angular_gallery
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: '>=0.2.6 <0.5.0'
