name: angular_gallery
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.8.1 <3.0.0'
dependencies:
  angular: ^6.0.0
  angular_components: 0.15.0
  angular_forms: ^3.0.0
  angular_router: 2.0.0
  build: '>=0.11.1 <2.0.0'
  build_config: '>=0.2.6 <0.5.0'
  mustache: ^1.0.0

dependency_overrides:
  angular_components:
    path: ../angular_components
  angular:
    git:
      url: git://github.com/dart-lang/angular.git
      path: angular
  angular_ast:
    git:
      url: git://github.com/dart-lang/angular.git
      path: angular_ast
  angular_compiler:
    git:
      url: git://github.com/dart-lang/angular.git
      path: angular_compiler
  angular_forms:
    git:
      url: git://github.com/dart-lang/angular.git
      path: angular_forms
