name: angular_gallery
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.1.0-dev.9.4 <3.0.0'
dependencies:
  angular: ^5.1.0
  angular_components: 0.10.1
  angular_forms: ^2.1.0
  angular_router: 2.0.0-alpha+20
  build: '>=0.11.1 <2.0.0'
  build_config: '>=0.2.6 <0.4.0'
  mustache: ^1.0.0
