name: material_checkbox_example
publish_to: none

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  angular: ^6.0.0
  angular_components: ^1.0.0
  angular_forms: ^3.0.0
  angular_gallery:
    path: ../../angular_gallery
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: '>=0.2.6 <0.5.0'
